### ISSUE TITLE
Internal service header - Service name out of alignment

### ISSUE THREAD

**Issue by mitz-lad** [dwp/design-system#486] opened 2022-10-05 09:50 UTC
## Describe the issue
Service name is out of alignment using the example code from [Internal service header component](https://design-system.dwp.gov.uk/components/internal-service-header).

This issue is also related to [Header - Alignment issues + BEM issue](https://gitlab.com/dwp/dwp-design-system/frontend/-/issues/12)

> With [[3300a42b](https://gitlab.com/dwp/dwp-design-system/frontend/-/commit/3300a42bf111b7977218cab8cf5105e7064ae477)]we have added padding to the service-name section without an action that causes it to misalignment with keybar details
> 
> Also noticed that we have a class ```dwp-header__container--service-name``` given we don't have a ```dwp-header__container``` to modify I assume it should reviewed? 

## Steps to reproduce the issue
Use the first example code provided in the [Internal service header component](https://design-system.dwp.gov.uk/components/internal-service-header) to implement a header.

```
<header class="govuk-header dwp-header" data-module="govuk-header">
  <div class=" govuk-width-container "
    <a href="#" class="govuk-header__link govuk-header__link--service-name dwp-header__container--service-name">
      Service name
    </a>
  </div>
</header> 
```

Seems like the other examples in front end work because of the presence of `<div class="govuk-grid-row">` directly inside `<div class="govuk-width-container">`.

![dwp-design-system-review herokuapp com_examples_header-key-details](https://user-images.githubusercontent.com/72147702/194031159-acbebc2f-4fc9-40b6-93f3-c69108d1e8e3.png)

## Actual vs expected behaviour

- Service name sits in line with content without having to use `<div class="govuk-grid-row">` when it is not required
- If using ```dwp-header__container--service-name``` as the class than there should be a ```dwp-header__container``` to modify or use an existing block or create a new element class for the service name

**Comment by jonhurrell** [comment] 2022-10-07 10:38
@mitz-lad is this a duplicate of https://github.com/dwp/design-system/issues/465 or does it have additional bugs? cc @simoneduca

**Comment by mitz-lad** [comment] 2022-10-10 07:52
@jonhurrell for the alignment issue yes it is - didn't see that one! I can just copy the details above across to that ticket if it's easier? cc @simoneduca

**Comment by mitz-lad** [comment] 2022-10-10 09:47
@simoneduca merged the information from the gitlab ticket into this one - I left the screenshots out as the one in this ticket already highlights the issue.

**Comment by simoneduca** [comment] 2022-10-10 15:34
@mitz-lad as  far as I can see this is expected behaviour. Users have two options for the header: with or without container. I'm not sure what the issue is...

**Comment by mitz-lad** [comment] 2022-10-10 16:38
Discussed with @simoneduca on a call highlighting the current example introduces extra padding to the service name.

**Closed as completed** 2022-10-31 09:17 UTC
Labels: 🐞 bug, internal service header
